TRUNCATE TABLE "data_sources" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "data_source_fields" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "templates" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "template_fields" RESTART IDENTITY CASCADE;